language: bash

services:
  - docker

env:
  global:
    - LATEST_TAG=4.1
    - BASE_IMAGE_STABILITY_TAG=2.4.0
  matrix:
    - VARNISH_VER=4.1 TAG=4.1 EXTRA_TAG=4

script:
  - cd ./"${VARNISH_VER:0:1}"
  - make && make test

after_success:
  - bash "${TRAVIS_BUILD_DIR}/travis-release.sh"

notifications:
  on_failure: never
  slack:
    secure: |
      ZomVXB+VN4jP/9yemdbCKDrCNnvTEAbUeSbGJow4j0cJW5cjY7EZ2MSIiu7qK6J+vmIRRBqmbNt2xRnJiAj3cDZjZdTepy08fQPVPmjb5XWPufevFP5TJvKcOkNfAzCKk48dSA3liLI6U/cu2y33yL7JNocSM37nWxkFbfpwvZtJsWmASnn5CIrpV01MaccpB9YUFJnC1MdF6wBpb2Q6V/S1YNYV2hLQdOT3112Sj9Grtit7SHAjQtzbr7sCgWqZjB04QhUQcJeLov+sb0jgPLeFSceeI5iCXw7waExKoanQ4FYSZPugllf0/dVEFjcJVWCixvkG72MVgb6ASWlh190/Mf+dkFb0bU4zXkiC+MLi/evxzqe+jaQ3VR+/W+z47bsLsrOIZJRp83XtdgUsUyylZG6dbe4v55Shv6MU6s3nIrfcTg4LLsO/Pkkysl/yQ3U3DL9nr45aWYQcw0Po1P3CRX2l+5PrOOkYVBELsr1rHjSLbLd9bVCz9zhhfRCdayOJUTIFT7aAhpCmMlMGm/UIp5g4H8JhKoezSuU39hv2kKhYFfgvVMHn3JDpqHIxg5IYU1U12L5GnDyXeOX56hzWY48YMHt1GoTuRtkymN295srcxpKG+mjxoe3JlWtD38HrY3zpqGoKATGDyKrM0gjoXlJABm7nIPOuwBjtEq0=
